#!/bin/bash

while true; do
  # remember current window
  # focused_window_id=$(xdotool getwindowfocus)

  # send keystroke to refresh
  # xdotool search --onlyvisible --name "@dev" windowfocus key "1+Return+2+2+Return+3+3+3+Return+1+3+2+1+3+2+Return+1+3+2+1+3+2+Return+1+3+2+Return+1+3+2+1+3+2+Return+1+3+2+1+3+2+Return+1+3+2+1+3+2+Return+1+3+2+1+3+2+Return"
  # xdotool search --onlyvisible --name "@dev" windowfocus key "1+Return+2+2+Return+3+3+3+Return+1+2+3+Return+Return" 
  xdotool search --onlyvisible --name "@dev" windowfocus key "Return+2+2+Return+3+3+3+Return+1+2+3+Return+Return" 
  # xdotool search --onlyvisible --name "@dev" windowfocus key "1+2+3+3+2+1+2+3+3+1+2+Return" 
  # xdotool search --onlyvisible --name "@dev" windowfocus key "3+2+3+3+2+1+1+2+3+3+2+1+2+3+3+1+2+Return" 
  # xdotool search --onlyvisible --name "@dev" windowfocus key "1+2+3+3+2+1+2+3+3+1+2+Return" 
  # xdotool search --onlyvisible --name "@dev" windowfocus key "3+2+3+3+2+1+1+2+3+3+2+1+2+3+3+1+2+Return" 

  # switch window, sync to "wait"
  # xdotool windowactivate --sync $focused_window_id

  sleep 1
done
